## Copyright 2019 Diffblue Limited. All Rights Reserved.
version: 2
commands:
  test-nodejs:
    steps:
      - run:
          name: Check yarn version
          command: yarn --version
      - run:
          name: Check node version
          command: node --version
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Test
          command: yarn test
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn  
jobs:
  test-node-v8:
    docker:
      - image: node:8
    steps:
      - test-nodejs
  test-node-v10:
    docker:
      - image: node:10
    steps:
      - test-nodejs
  test-node-v11:
    docker:
      - image: node:11
    steps:
      - test-nodejs

workflows:
  test-supported-node-versions:
    jobs:
      - test-node-v8
      - test-node-v10
      - test-node-v11
