## Copyright 2019 Diffblue Limited. All Rights Reserved.

version: 2.1

references:
  yarn_cache_key: &yarn_cache_key
    v1-dependency-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
  yarn_backup_cache_key: &yarn_backup_cache_key
    v1-dependency-yarn-{{ .Branch }}-
  yarn_backup_cache_key_no_branch: &yarn_backup_cache_key_no_branch
    v1-dependency-yarn-

commands:
  test-node:
    steps:
      - run:
          name: Check yarn version
          command: yarn --version
      - run:
          name: Check node version
          command: node --version
      - checkout
      - restore_cache:
          keys:
            - *yarn_cache_key
            - *yarn_backup_cache_key
            - *yarn_backup_cache_key_no_branch
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Lint
          command: yarn lint-ts
      - run:
          name: Copyright check
          command: yarn copyright-check
      - run:
          name: License check
          command: yarn license-check check-file
      - run:
          name: Test
          command: yarn test
      - save_cache:
          name: Save yarn package cache
          key: *yarn_cache_key
          paths:
            - ~/.cache/yarn

jobs:
  test-node-v8:
    docker:
      - image: circleci/node:8.16.0
    steps:
      - test-node
  test-node-v10:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - test-node
  test-node-v11:
    docker:
      - image: circleci/node:11.14.0
    steps:
      - test-node

workflows:
  test-supported-node-versions:
    jobs:
      - test-node-v8
      - test-node-v10
      - test-node-v11
