## Copyright 2019 Diffblue Limited. All Rights Reserved.

version: 2.1

references:
  yarn_cache_key: &yarn_cache_key
    v1-dependency-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
  yarn_backup_cache_key: &yarn_backup_cache_key
    v1-dependency-yarn-{{ .Branch }}-
  yarn_backup_cache_key_no_branch: &yarn_backup_cache_key_no_branch
    v1-dependency-yarn-
  node-8: &node-8
    circleci/node:8.16.0
  node-10: &node-10
    circleci/node:10.15.3
  node-11: &node-11
    circleci/node:11.14.0

commands:
  install-dependencies:
    steps:
      - run:
          name: Yarn version
          command: yarn --version
      - restore_cache:
          keys:
            - *yarn_cache_key
            - *yarn_backup_cache_key
            - *yarn_backup_cache_key_no_branch
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

  cache-dependencies:
    steps:
      - save_cache:
          name: Save yarn package cache
          key: *yarn_cache_key
          paths:
            - ~/.cache/yarn

  checks:
    steps:
      - run:
          name: Lint Typescript code
          command: yarn lint-ts
      - run:
          name: Check all files have up to date copyright notices
          command: yarn copyright-check
      - run:
          name: Check all third party licenses are approved
          command: yarn license-check check-file

  tests:
    steps:
      - run:
          name: Unit tests
          command: yarn coverage --forbid-only --forbid-pending
      - run:
          name: Integration tests
          command: yarn integration-test --forbid-only --forbid-pending

  deploy:
    steps:
      - run:
          name: Publish package
          command: yarn publish-package $NPM_TOKEN
      - run:
          name: Create git tag
          command: yarn create-release-tag
      - run:
          name: Create a pull request from the release back to develop
          command: create-post-release-pull-request $GITHUB_TOKEN

jobs:
  checks:
    docker:
      - image: *node-10
    steps:
      - checkout
      - install-dependencies
      - checks
      - cache-dependencies

  test-node-8:
    docker:
      - image: *node-8
    steps:
      - checkout
      - install-dependencies
      - tests
      - cache-dependencies

  test-node-10:
    docker:
      - image: *node-10
    steps:
      - checkout
      - install-dependencies
      - tests
      - cache-dependencies

  test-node-11:
    docker:
      - image: *node-11
    steps:
      - checkout
      - install-dependencies
      - tests
      - cache-dependencies

  deploy:
    docker:
      - image: *node-10
    steps:
      - checkout
      - install-dependencies
      - deploy
      - cache-dependencies

workflows:
  test:
    jobs:
      - checks
      - test-node-8
      - test-node-10
      - test-node-11
      - deploy:
          requires: [checks, test-node-8, test-node-10, test-node-11]
          filters:
            branches:
              only: master
